CREATE TABLE PRODUCTO_FACTURA(
    profac_id int PRIMARY KEY,
    profac_cantidad int,
    fac_id int,
    pro_id int,
    FOREIGN KEY (fac_id) REFERENCES FACTURA (fac_id),
    FOREIGN KEY (pro_id) REFERENCES PRODUCTO (pro_id)
);

INSERT INTO PRODUCTO_FACTURA VALUES (1,5,1,1);
INSERT INTO PRODUCTO_FACTURA VALUES (2,10,1,2);
INSERT INTO PRODUCTO_FACTURA VALUES (3,15,1,3);
INSERT INTO PRODUCTO_FACTURA VALUES (4,22,2,1);
INSERT INTO PRODUCTO_FACTURA VALUES (5,25,2,2);
INSERT INTO PRODUCTO_FACTURA VALUES (6,31,2,3);
INSERT INTO PRODUCTO_FACTURA VALUES (7,35,3,1);
INSERT INTO PRODUCTO_FACTURA VALUES (8,44,3,2);
INSERT INTO PRODUCTO_FACTURA VALUES (9,1,3,3);